services:
  caddy:
    volumes:
      - ../verification/playwright-oid4vp/Caddyfile:/etc/caddy/Caddyfile
  wallet-api:
    build:
      context: ../
      dockerfile: waltid-services/waltid-wallet-api/Dockerfile
  verifier-api:
    environment:
      VERIFIER_API_PORT: "7303"
    ports:
      - "7303:7303"
    build:
      context: ../
      dockerfile: waltid-services/waltid-verifier-api/Dockerfile
  verifier-api2:
    ports:
      - "7304:7004"
    volumes:
      - ../verification/playwright-oid4vp/verifier-api2/verifier-service.conf:/waltid-verifier-api2/config/verifier-service.conf
    build:
      context: ../
      dockerfile: waltid-services/waltid-verifier-api2/Dockerfile
  web-portal:
    environment:
      NEXT_PUBLIC_VERIFIER: "http://$SERVICE_HOST:7303"
      NEXT_PUBLIC_VERIFIER2: "http://$SERVICE_HOST:7304"
