# Uncomment the next line to define a global platform for your project
platform :ios, '15.4'

target 'waltid.crypto.ios.utils' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for waltid.crypto.ios.utils
  pod 'JOSESwift'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXPLICIT_MODULES_IN_WORKSPACE'] = 'NO'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
      config.build_settings['SWIFT_VERSION'] = '5.0'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'x86_64 i386'
    end
  end
end
